# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified on'),
        ),
        migrations.AddField(
            model_name='scan',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created on'),
            preserve_default=False,
        ),
    ]
