# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_auto_20170318_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='book', to='gui.Tag'),
        ),
    ]
